services:
  adaptiveai-personaar-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptiveai-personaar-frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_PERSONA_ENGINE_URL=http://localhost:5001
      - REACT_APP_DIALOG_ORCHESTRATOR_URL=http://localhost:5002
    networks:
      - persona_network

networks:
  persona_network:
    external: true
